version: '3.8'

services:
  # Contenedor principal con Jupyter, Spark y entorno visual
  workspace:
    build: .                      # Construye la imagen usando el Dockerfile local
    container_name: bigdata_workspace
    platform: linux/amd64
    ports:
      - "8888:8888"               # Jupyter Lab
      - "4040:4040"               # Interfaz web de Spark
      - "5901:5900"               # Cambiado a 5901 para evitar el bloqueo del puerto 5900
      - "6081:6080"               # Cambiado a 6081 para evitar conflictos en el navegador
      - "8501:8501" 		  # Acceso a Streamlite

    volumes:
      - .:/home/jovyan/work       # Monta la carpeta del proyecto dentro del contenedor
    environment:
      - JUPYTER_ALLOW_INSECURE_WRITES=true  # Permite escritura en volúmenes montados
      - DISPLAY=:99               # Pantalla virtual usada por el entorno gráfico
      - JUPYTER_ENABLE_LAB=yes    # Fuerza el uso de JupyterLab de forma explícita
    shm_size: "2gb"               # Evita fallos del navegador por poca memoria compartida
    depends_on:
      - database
    dns:
      - 8.8.8.8
    restart: always
    networks:
      - bigdata_net

  # Contenedor de base de datos MongoDB LOCAL (Puerto cambiado para evitar bloqueos)
  database:
    image: mongo:latest
    container_name: bigdata_mongodb
    platform: linux/amd64
    ports:
      - "27019:27017"             # Cambiado a 27019 para que no choque con el puerto bloqueado
    volumes:
      - mongo_data:/data/db       # Guarda los datos de forma persistente
    restart: always
    networks:
      - bigdata_net

# Volumen persistente para MongoDB LOCAL
volumes:
  mongo_data:

# Red personalizada para comunicación interna
networks:
  bigdata_net:
    driver: bridge
    name: BigData_Network_UCN